### ISSUE TITLE
Support google-protobuf >= 4.26 in gemspec

### ISSUE THREAD

**Issue by qnighy** [googleapis/common-protos-ruby#267]
## Problem

[protobuf v26.0](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0) had been released, and it contains [breaking changes to the Ruby runtime](https://protobuf.dev/news/2023-12-27/). This resulted in the gem being bumped from 3.25 to 4.26.

However, as `googleapis-common-protos-types` and `grpc` restricts the `google-protobuf` version within 3.x, the new version is virtually unavailable as of now.

## Expected solution

The version restriction is relaxed from `"~> 3.18"` to `">= 3.18", "< 5.0"`. Additionally, incompatibilities are fixed if any. Note that the biggest change (to my understanding) is the Ruby DSL removal and it is already resolved in #165.

**Comment by dazuma** [comment]
Thanks @qnighy! Yes, we will get a relaxed version restriction through the rest of the api clients stack once we've been able to verify compatibility.

**Comment by colinbendell** [comment]
What is the expected eta of supporting the 4.x series?
