### ISSUE TITLE
Error: cannot load such file -- google/protobuf/descriptor_pb and google/cloud/logging/v2 (LoadError) when using version 1.3.1

### ISSUE THREAD

**Issue by q-ahmedsalman** [googleapis/common-protos-ruby#68]
#### Environment details

  - Programming language: Ruby
  - OS: Alpine
  - Language runtime version: 
    - ruby 2.7.5p203
    - gem 3.1.6
    - bundler 2.0.1
  - Package version: 1.3.1

#### Steps to reproduce

  1. A bit of context, this library is being installed as part of Gemfile dependency tree and used in our docker fluentd image. 
    for example `exec fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --gemfile /fluentd/Gemfile`
  2. However fluentd started failing as soon as the library updated from 1.3.0 to 1.3.1, sample error:
        <details>
        <summary><b>Click to view error log</b></summary>

        ```/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/protobuf/descriptor_pb (LoadError)
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/googleapis-common-protos-types-1.3.1/lib/google/api/annotations_pb.rb:5:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/google-cloud-logging-1.6.6/lib/google/logging/v2/logging_config_pb.rb:7:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2/config_service_v2_client.rb:28:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2.rb:16:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluent-plugin-google-cloud-0.10.8/lib/fluent/plugin/out_google_cloud.rb:24:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:102:in `block in search'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:99:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:99:in `search'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:44:in `lookup'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:155:in `new_impl'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:109:in `new_output'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:72:in `block in configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/out_copy.rb:38:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:173:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:132:in `add_match'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:74:in `block in configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:146:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/engine.rb:105:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/engine.rb:80:in `run_configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>'
                from /fluentd/vendor/bundle/ruby/2.3.11/bin/fluentd:23:in `load'
                from /fluentd/vendor/bundle/ruby/2.3.11/bin/fluentd:23:in `<main>'
        /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/cloud/logging/v2 (LoadError)
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluent-plugin-google-cloud-0.10.8/lib/fluent/plugin/out_google_cloud.rb:24:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:102:in `block in search'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:99:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:99:in `search'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/registry.rb:44:in `lookup'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:155:in `new_impl'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:109:in `new_output'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:72:in `block in configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin/out_copy.rb:38:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/plugin.rb:173:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:132:in `add_match'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:74:in `block in configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `each'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:146:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/engine.rb:105:in `configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/engine.rb:80:in `run_configure'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
                from /fluentd/vendor/bundle/ruby/2.3.11/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>'
                from /fluentd/vendor/bundle/ruby/2.3.11/bin/fluentd:23:in `load'
                from /fluentd/vendor/bundle/ruby/2.3.11/bin/fluentd:23:in `<main>'```
        </details>
  3. The Gemfile the image is installing looks like this:
        <details>
        <summary><b>Click to view Gemfile</b></summary>

        ```source "https://rubygems.org"

        gem "fluentd", "1.11.2"
        gem "oj", "3.8.1"
        gem "grpc", "1.31.1"
        gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
        gem "fluent-plugin-concat", "~> 2.3.0"
        gem "fluent-plugin-grok-parser", "~> 2.5.0"
        gem "fluent-plugin-prometheus", "~> 1.5.0"
        gem 'fluent-plugin-json-in-json-2', ">= 1.0.2"
        gem "fluent-plugin-record-modifier", "~> 2.0.0"
        gem "fluent-plugin-rewrite-tag-filter", "~> 2.2.0"
        gem "fluent-plugin-gcs", "0.4.0"
        gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.3.0"
        gem "fluent-plugin-google-cloud", "0.10.8"
        gem "ffi"
        gem "json", "2.2.0"
        gem "bigdecimal", "1.4.4"```

#### Discussion
We are uncertain about this error, the library `googleapis-common-protos-types` is being pulled dynamically through dependency tree i.e. we don't specify it in the tree. The runtime of fluentd started throwing error as soon as the version changed from `1.3.0` to `1.3.1`.  From our understanding this type of version change should not be breaking. Any information that could help us understand whats going on pls ?

Thanks!

**Comment by dazuma** [comment]
Hi, sorry about that. I'm not sure why `require "google/protobuf/descriptor_pb"` was added, but it seems to have disappeared again now when I rerun code generation. I've released version 1.3.2 with that change. Does that version work better?
