### ISSUE TITLE
v1.4.0 seems to be released already but not registered on rubygems.org

### ISSUE THREAD

**Issue by ha4gu** [googleapis/common-protos-ruby#97]
googleapis-common-protos 1.4.0 seems to be released on 18 Aug 2022 on [Releases page](https://github.com/googleapis/common-protos-ruby/releases).

However on [rubygems.org](https://rubygems.org/gems/googleapis-common-protos), the latest version is still 1.3.12.
You might forget to upload 1.4.0 gem to rubygems.org....

**Comment by bajajneha27** [comment]
Hi @ha4gu 
Thanks for bringing this to our notice. We've published the version to [rubygems.org](https://rubygems.org/gems/googleapis-common-protos) now.  We're working on it to make sure this doesn't happen again.
